-- Intentionally empty. The client image-replacement wrapper lives in
-- `_shims_client.lua`, whose explicit fxmanifest entry loads after every
-- adapter. This file is matched mid-glob by `modules/inventory/**/client.lua`,
-- so any logic here would wrap adapters twice or too early. It must stay
-- present so the auto-updater overwrites stale copies -- updates write files
-- but never delete them.
