-- Intentionally empty. The image-replacement and inventory-sync wrappers live
-- in `_shims_server.lua`, whose explicit fxmanifest entry loads after every
-- adapter. This file is matched mid-glob by `modules/inventory/**/server.lua`,
-- so any logic here would wrap adapters twice (duplicate updateInventory
-- events) or wrap too early. It must stay present so the auto-updater
-- overwrites stale copies -- updates write files but never delete them.
